
IF (EXISTS(
		SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Address' AND TABLE_SCHEMA='tmp')
	AND 
	EXISTS(
		SELECT TOP 1 1 FROM dbo.[Address]))
			BEGIN
				DROP TABLE tmp.[Address]
			END

IF (EXISTS(
		SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Customer' AND TABLE_SCHEMA='tmp')
	AND 
	EXISTS(
		SELECT TOP 1 1 FROM dbo.[Customer]))
			BEGIN
				DROP TABLE tmp.[Customer]
			END

IF (EXISTS(
		SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='FactInternetSales' AND TABLE_SCHEMA='tmp')
	AND
	EXISTS(
		SELECT TOP 1 1 FROM dbo.[FactInternetSales]))
			BEGIN
				DROP TABLE tmp.[FactInternetSales]
			END