
IF (NOT EXISTS(
		SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='FK_Customer_Address'))
			BEGIN
				ALTER TABLE Customer Add CONSTRAINT FK_Customer_Address FOREIGN KEY (AddressID) REFERENCES Address(ID)
			END
